#!/bin/sh
echo "Running system initialization..."
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
hostname Sos

echo "Load drivers"
insmod /lib/modules/hello_driver.ko

echo "Starting system services"
/bin/hello & 

echo "Initialization complete."
